# Generated by Django 2.1.1 on 2018-11-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface_app', '0002_auto_20181130_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtask',
            name='cases',
            field=models.TextField(blank=True, default='', null=True, verbose_name='关联用例'),
        ),
    ]
